spring:
  application:
    name: CONFIGSERVER
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/xrodrigo1982x/microservices-configurations
      discovery:
        enabled: true

info:
  artifact: ${project.artifactId}
  name: ${spring.application.name}
  description: ${project.description}
  version: ${project.version}