spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: false

eureka:
  enableSelfPreservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${appName}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    instanceEnabledOnit: true

cassandra:
    keyspace: configserver