spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: false

eureka:
  enableSelfPreservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    instanceEnabledOnit: true

cassandra:
    host: 172.17.0.1
    keyspace: configserver